CREATE TABLE IF NOT EXISTS flows_ledger (
  day           TEXT PRIMARY KEY CHECK (day GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  ticks         INTEGER NOT NULL DEFAULT 0,
  t1_last_at    INTEGER,
  t1_gap_ms     INTEGER NOT NULL DEFAULT 0,
  t1_gap_end    INTEGER,
  t1_ok         INTEGER NOT NULL DEFAULT 0,
  t1_fail       INTEGER NOT NULL DEFAULT 0,
  t1_ok_at      INTEGER,
  t1_ok_gap_ms  INTEGER NOT NULL DEFAULT 0,
  t1_ok_gap_end INTEGER,
  focus_ok      INTEGER NOT NULL DEFAULT 0,
  focus_partial INTEGER NOT NULL DEFAULT 0,
  focus_fail    INTEGER NOT NULL DEFAULT 0,
  focus_ok_at   INTEGER,
  focus_gap_ms  INTEGER NOT NULL DEFAULT 0,
  focus_gap_end INTEGER,
  t2_passes     INTEGER NOT NULL DEFAULT 0,
  t2_first_at   INTEGER,
  t2_last_at    INTEGER,
  t2_gap_ms     INTEGER NOT NULL DEFAULT 0,
  t2_gap_end    INTEGER,
  t2_calls      INTEGER NOT NULL DEFAULT 0,
  t2_failed     INTEGER NOT NULL DEFAULT 0,
  stale_ticks   INTEGER NOT NULL DEFAULT 0,
  stale_over_s  INTEGER,
  stale_key     TEXT,
  nightly_at    INTEGER,
  nightly_runs  INTEGER NOT NULL DEFAULT 0,
  updated_at    INTEGER NOT NULL
);
