const entry = (status, message) => Object.freeze([status, message]);

export const ERRORS = Object.freeze({
  account_changed: entry(409, "Signed-in account changed; refresh and try again"),
  archive_immutable: entry(409, "A dated archive key already holds a different payload"),
  archive_permanent: entry(409, "A permanent archive key already holds a different payload"),
  archive_raced: entry(409, "The dated archive key was written by another run in between"),
  archive_unreadable: entry(503, "The dated archive key could not be read"),
  attempt_conflict: entry(409, "Attempt id was already used for different data"),
  bad_json: entry(400, "Send a JSON object"),
  brief_unreadable: entry(500, "The stored brief could not be read"),
  chain_empty: entry(404, "No listed options found for that symbol"),
  chain_no_spot: entry(502, "No regular-session price for that symbol"),
  chain_rate_limited: entry(429, "Market data provider is rate limiting"),
  chain_timeout: entry(504, "Market data provider did not answer in time"),
  chain_too_large: entry(502, "Market data provider body is over the parse ceiling"),
  chain_unconfigured: entry(503, "Live chain lookup is not configured"),
  chain_upstream: entry(502, "Market data provider returned an error"),
  forbidden: entry(403, "Forbidden"),
  internal_error: entry(500, "Internal server error"),
  invalid_expiry: entry(400, "Expiry must be YYYY-MM-DD"),
  invalid_json: entry(400, "Body must be a valid JSON object"),
  invalid_key: entry(400, "Unknown payload key"),
  invalid_mastery_attempt: entry(400, "Review item and attempt data must be valid"),
  invalid_payload: entry(400, "Payload is not valid JSON"),
  invalid_placement: entry(400, "Placement result must be valid"),
  invalid_preferences: entry(400, "Learning preferences must be valid"),
  invalid_progress: entry(400, "Model and completed stages must be valid"),
  invalid_project: entry(400, "Project mode and task completion must be valid"),
  invalid_skill_attempt: entry(400, "Skill, item, and attempt data must be valid"),
  invalid_stats: entry(400, "Streak and activity date must be valid"),
  invalid_ticker: entry(400, "Unknown ticker"),
  invalid_topic: entry(400, "Unknown topic"),
  live_token_scope: entry(403, "The live token reads one key at a time"),
  method_not_allowed: entry(405, "Method not allowed"),
  no_question: entry(400, "Ask a question in the `question` field."),
  not_found: entry(404, "Not found"),
  payload_too_large: entry(413, "Payload is too large"),
  rate_limited: entry(429, "Too many requests; try again shortly."),
  reset_required: entry(409, "Learning progress was reset; refresh synchronized state and try again"),
  rt_forbidden: entry(403, "Real-time access is limited to the owner"),
  rt_off: entry(404, "The real-time rail is off"),
  rt_unavailable: entry(503, "The real-time rail is unavailable"),
  service_unavailable: entry(503, "Service is temporarily unavailable"),
  store_quota: entry(503, "The store's daily quota is spent; it resets at 00:00 UTC"),
  store_unreadable: entry(503, "The store could not be read"),
  too_large: entry(413, "Payload is too large"),
  too_many_keys: entry(400, "Too many keys in one request"),
  unauthorized: entry(401, "Authentication required"),
  undeletable_key: entry(400, "That key cannot be removed"),
  unavailable: entry(503, "Service is not configured"),
  unsupported_media_type: entry(415, "Content-Type must be application/json"),
  upgrade_required: entry(426, "Expected a WebSocket upgrade"),
});

export const errorEntry = (code) => (Object.hasOwn(ERRORS, code) ? ERRORS[code] : null);
